sudo: false
language: ruby

cache: bundler
bundler_args: ""

branches:
  only: master

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile

matrix:
  exclude:
    - rvm: 2.3.1
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails5.0.gemfile
